return {
	Accent = Color3.fromRGB(180, 145, 70),
	Background = Color3.fromRGB(28, 26, 21),
	Border = Color3.fromRGB(60, 56, 48),

	Text = {
		Primary = Color3.fromRGB(255, 255, 255),
		Secondary = Color3.fromRGB(200, 200, 200),
		Tertiary = Color3.fromRGB(160, 160, 160),
		Quaternary = Color3.fromRGB(115, 115, 115),
		Quinary = Color3.fromRGB(0, 0, 0),
		Senary = Color3.fromRGB(215, 215, 215)
	},
}