return {
	Accent = Color3.fromRGB(100, 100, 100),
	Background = Color3.fromRGB(25, 25, 25),
	Border = Color3.fromRGB(55, 55, 55),

	Text = {
		Primary = Color3.fromRGB(255, 255, 255),
		Secondary = Color3.fromRGB(200, 200, 200),
		Tertiary = Color3.fromRGB(160, 160, 160),
		Quaternary = Color3.fromRGB(115, 115, 115),
		Quinary = Color3.fromRGB(0, 0, 0),
		Senary = Color3.fromRGB(215, 215, 215)
	},
}