return {
	Accent = Color3.fromRGB(60, 120, 180),
	Background = Color3.fromRGB(22, 26, 30),
	Border = Color3.fromRGB(50, 56, 64),

	Text = {
		Primary = Color3.fromRGB(255, 255, 255),
		Secondary = Color3.fromRGB(200, 200, 200),
		Tertiary = Color3.fromRGB(160, 160, 160),
		Quaternary = Color3.fromRGB(115, 115, 115),
		Quinary = Color3.fromRGB(0, 0, 0),
		Senary = Color3.fromRGB(215, 215, 215)
	},
}